-- Seed data for activities
insert into activities (name, description, image_url, category, price, duration, difficulty, depth, rating, review_count, marine_life, is_featured)
values
  (
    'Cedar Pride Wreck',
    'A legendary 74-meter Lebanese freighter resting on its side at 25 meters. Home to lionfish, groupers, and stunning soft corals.',
    '/images/cedar-pride.jpg',
    'Diving',
    65.00,
    '2-3 hours',
    'Intermediate',
    'Medium',
    4.9,
    245,
    ARRAY['Lionfish', 'Groupers', 'Soft Corals', 'Barracuda'],
    true
  ),
  (
    'Japanese Garden',
    'Beautiful coral formations resembling a manicured garden. Perfect for beginners with shallow depths and calm waters.',
    '/images/japanese-garden.jpg',
    'Diving',
    45.00,
    '2 hours',
    'Beginner',
    'Shallow',
    4.8,
    312,
    ARRAY['Sea Turtles', 'Clownfish', 'Hard Corals', 'Moray Eels'],
    true
  ),
  (
    'Rainbow Reef',
    'Vibrant coral reef teeming with colorful fish. Named for the spectrum of colors you''ll encounter.',
    '/images/rainbow-reef.jpg',
    'Diving',
    40.00,
    '1.5 hours',
    'Beginner',
    'Shallow',
    4.7,
    189,
    ARRAY['Anthias', 'Butterflyfish', 'Parrotfish', 'Sea Stars'],
    false
  ),
  (
    'Seven Sisters',
    'Seven coral pinnacles rising from the sandy bottom, each hosting unique marine communities.',
    '/images/seven-sisters.jpg',
    'Diving',
    55.00,
    '2 hours',
    'Intermediate',
    'Medium',
    4.8,
    156,
    ARRAY['Rays', 'Nudibranchs', 'Octopus', 'Scorpionfish'],
    false
  ),
  (
    'The Tank (Military Museum)',
    'Unique underwater military museum featuring a sunken tank and armored vehicles. An unforgettable experience.',
    '/images/tank-wreck.jpg',
    'Diving',
    50.00,
    '1.5 hours',
    'Beginner',
    'Shallow',
    4.6,
    278,
    ARRAY['Anemones', 'Damselfish', 'Cardinalfish'],
    true
  ),
  (
    'Gorgonian I & II',
    'Famous for spectacular gorgonian sea fans and black coral. Advanced dive with stronger currents.',
    '/images/gorgonian.jpg',
    'Diving',
    85.00,
    '3 hours',
    'Advanced',
    'Deep',
    4.9,
    98,
    ARRAY['Gorgonian Fans', 'Black Coral', 'Sharks', 'Eagle Rays'],
    false
  ),
  (
    'Discover Scuba Diving',
    'Your first breath underwater! No experience needed. Includes full instruction and equipment.',
    '/images/intro-dive.jpg',
    'Diving',
    75.00,
    '3 hours',
    'Beginner',
    null,
    4.9,
    423,
    null,
    true
  ),
  (
    'Snorkeling Adventure',
    'Explore multiple snorkeling spots with a guide. See turtles, colorful fish, and pristine reefs.',
    '/images/snorkel-tour.jpg',
    'Snorkeling',
    35.00,
    '2 hours',
    'Beginner',
    null,
    4.7,
    567,
    null,
    true
  ),
  (
    'Glass Bottom Boat Tour',
    'Perfect for non-swimmers! See the underwater world through the boat''s glass floor.',
    '/images/glass-boat.jpg',
    'Boat Tour',
    25.00,
    '1.5 hours',
    null,
    null,
    4.5,
    312,
    null,
    false
  ),
  (
    'Sunset Yacht Cruise',
    'Romantic sunset cruise with refreshments. Watch the sun set over the Red Sea mountains.',
    '/images/sunset-cruise.jpg',
    'Boat Tour',
    55.00,
    '2.5 hours',
    null,
    null,
    4.8,
    234,
    null,
    true
  ),
  (
    'Jet Ski Adventure',
    'Feel the adrenaline! Explore Aqaba''s coastline on a powerful jet ski with safety briefing included.',
    '/images/jet-ski.jpg',
    'Water Sports',
    45.00,
    '30 mins',
    null,
    null,
    4.6,
    189,
    null,
    false
  ),
  (
    'Parasailing Experience',
    'Soar above the Red Sea and enjoy breathtaking views of Aqaba, Eilat, and Saudi Arabia.',
    '/images/parasailing.jpg',
    'Water Sports',
    60.00,
    '15 mins flight',
    null,
    null,
    4.7,
    145,
    null,
    false
  );
